### ISSUE TITLE
Thresholds: 75% of hours per day.  70% days across time series. %5 missing days then avg prior/next day

### ISSUE THREAD

**Issue by ivanhanigan** [swish-climate-impact-assessment/BiosmokeValidatedEvents#5]
@farhadsalimi,
https://github.com/swish-climate-impact-assessment/BiosmokeValidatedEvents/blame/master/inst/doc/impute_aphea2_sydney_pm25.Rmd#L167
Talks about selecting the sites which have at least 75% of data available for each variable, but our protocol used 70%.  
I'd tried to make this accessible (modifiable) in this function:
https://github.com/swish-climate-impact-assessment/BiosmokeValidatedEvents/blob/master/R/sites_todo.R

**Comment by ivanhanigan** [comment]
@farhadsalimi, also this 5% rule.  Comes from http://www.invs.sante.fr/publications/2001/apheis/Apheis_p101-136.pdf p110.
So we need to first check before running line 263
https://github.com/swish-climate-impact-assessment/BiosmokeValidatedEvents/blame/master/inst/doc/impute_aphea2_sydney_pm25.Rmd#L263

**Comment by farhadsalimi** [comment]
@ivanhanigan  will do that Ivan, does it mean that if it is more than 5%, then do nothing?

**Comment by ivanhanigan** [comment]
yes, don't avg pre-or-post days at all

**Comment by farhadsalimi** [comment]
@ivanhanigan 
i followed them (http://jech.bmj.com/content/50/Suppl_1/S12.full.pdf+html)
thats why i used 75% hourly and whole time series.
What do you think?

**Comment by ivanhanigan** [comment]
hmmm I think I am getting confused about which sources we follow.
the link above is to
Katsouyanni, K., Schwartz, J., Spix, C., Touloumi, G., Zmirou, D.,
Zanobetti, A., … Anderson, H. R. (1996). Short term effects of air
pollution on health: a European approach using epidemiologic time series
data: the APHEA protocol. Journal of Epidemiology & Community Health,
50(Suppl 1), S12–S18. doi:10.1136/jech.50.Suppl_1.S12
who use three monthly avgs (but don't say if rolling/centred or calendar
season)

I have in my doco from years ago the
Touloumi, G., Samoli, E., Le Tetre, A., Atkinson, R., & Schwartz, J.
(2001). Annex 1 - APHEA2 Methodology. Air Pollution and Health: a European
Information System (APHEIS). Retrieved from
http://www.invs.sante.fr/publications/2001/apheis/
which used yearly averages

In our paper (2011) we cite Atkinson, R. W., Anderson, R. H., Sunyer, J.,
Ayres, J., Baccini, M., Vonk, J. M., … Katsouyanni, K. (2001). Acute
Effects of Particulate Air Pollution on Respiratory Admissions. American
Journal of Respiratory and Critical Care Medicine, 164(10), 1860–1866.
doi:10.1164/ajrccm.164.10.2010138
and ATKINSON, R. W., ROSS ANDERSON, H., SUNYER, J., AYRES, J., BACCINI, M.,
VONK, J. M., … KATSOUYANNI, K. (2001). Online Supplement for: ACUTE EFFECTS
OF PARTICULATE AIR POLLUTION ON RESPIRATORY ADMISSIONS. American Journal of
Respiratory and Critical Care Medicine, 164(10).
But they do not specify.

I think Fay used that ref for simplicity. In reality the
3mo-rolling-centred approach probably originated in the code that Geoff and
Richard Summerhayes.

I reckon we go with your R code that does calendar season, and cite the
Katsouyanni paper, but we should also note that this differs to the
protocol used in Johnston et al 2011.
We can always check later if it makes a difference.

**Comment by ivanhanigan** [comment]
apology, my comment above was not directly about about thresholds.  I see
Karsouyanni say 75% of days across time series, but in Johnston 2011 we
went with 70% days across the time-series after looking at our local data.
I think we can still follow the rule that we cite Katsouyanni for
imputation and refer to Johnston 2011 regarding the protocol that I used.

**Comment by ivanhanigan** [comment]
@farhadsalimi thanks for sorting the 5% rule.
I'm going to start a new issue regarding the number of sites to use as Geoff's instructions are a bit complicated.
